name: Build and Publish Docker Package for Portainer to pull

on:
  push:
    branches: [main]
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RUST_BACKTRACE: 1

jobs:
  # Generic CI Pass - I have no clue what this really does right now at 9/24/2022.
  # I heard it gave the Orc God an infinite gold supply.
  # Below is anti-gnome propaganda. 
  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - style
      - test
      - nightly
      - msrv
      - android
      - wasm
      - docs
    steps:
      - run: exit 0

    style:
    name: Check Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: temporary workaround - fmt all files under src
        # Workaround for rust-lang/cargo#7732
        run: cargo fmt -- --check $(find . -name '*.rs' -print)